### ISSUE TITLE
[Util] Support fuzzy search through bookmarks

### ISSUE THREAD

**Issue by ghost** [n2kia4/bkm#2]
Small util to integrate fuzzy search with fzf.

**Comment by n2kia4** [comment]
Thanks for the suggestion. I think that it is better not to integrate with [fzf](https://github.com/junegunn/fzf), but to use [Skim](https://github.com/lotabout/skim) internally.

**Comment by ghost** [comment]
I've just setup all thing around `fzf` and now againt skim, what a joke :)

leave the core and wrap around using skim? good?
